trigger:
  branches:
      include:
        - main

pr:
  branches:
      include:
        - feature/sprint-1-feature

parameters:
  - name: environment
    displayName: Choose Environment
    type: string
    default: dev
    values:
      - dev
      - qa
      - prod

  - name: terraformAction
    displayName: Teraform Action
    type: string
    default: apply
    values:
      - plan
      - apply

pool: Aexion pool

stages:
  - stage: Terraform_install
    jobs:
      - job: Terraform
        steps:
        - task: TerraformInstaller@1
          inputs:
           terraformVersion: 'latest'

        - task: PowerShell@2
          inputs:
            targetType: 'inline'
            pwsh: false
            script: |
              Write-Host "Hello"
                      

